### ISSUE TITLE
Unable to load .osm files when running on docker

### ISSUE THREAD

**Issue by AlexNti** [kiegroup/optaweb-vehicle-routing#293]
Hello, i am trying to load the belgium-latest.osm.pbf configuration inside docker container but i am unable to do it. I have tried with the default dockerfile configuration of the project and also with the following configuration `
FROM adoptopenjdk/openjdk8:ubi-minimal-jre
ENV APP_ROUTING_ENGINE air
WORKDIR /opt/app
COPY . .
CMD ["java", "-jar", "optaweb-vehicle-routing.jar"]
EXPOSE 8080`
I am missing something here?

**Comment by justinwkUKM** [comment]
What did you do to make it work?

**Comment by AlexNti** [comment]
> What did you do to make it work?

Hello, i have edited the dockerfile as follows:

`FROM openjdk:8-jdk-alpine
ENV APP_ROUTING_ENGINE graphhopper
ENV APP_ROUTING_OSM_DOWNLOAD_URL http://download.geofabrik.de/europe/greece-latest.osm.pbf
ENV APP_REGION_COUNTRY_CODES GR
ENV APP_ROUTING_OSM_FILE greece-latest.osm.pbf
COPY target/*-exec.jar /opt/app/optaweb-vehicle-routing.jar
WORKDIR /opt/app
VOLUME /opt/app/local
CMD ["java", "-jar", "optaweb-vehicle-routing.jar"]
EXPOSE 8080`

**Comment by justinwkUKM** [comment]
Thanks a lot. That's very helpful. Earlier, my workaround was to make changes in the application.properties file and not in the Dockerfile to run the project as expected.

#App configuration
app.region.country-codes=MY
app.routing.osm-dir=local/openstreetmap
app.routing.gh-dir=local/graphhopper
app.routing.osm-file=malaysia-singapore-brunei-latest.osm.pbf
