### ISSUE TITLE
runLocally.sh doesn't work on macOS

### ISSUE THREAD

**Issue by yurloc** [kiegroup/optaweb-vehicle-routing#320]
```
$ ./runLocally.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
There is no last used VRP dir. Using the default.
VRP dir: /Users/jjarae/.optaweb-vehicle-routing
./runLocally.sh: line 24: declare: -l: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
VRP dir ‘�� does not exist. Do you want to create it now? [y/N]: ^C
```

**Comment by yurloc** [comment]
Tips from Chris:
- `cat name | tr '[:upper:]' '[:lower:]'` should be portable way to make a variable lowercase
- https://stackoverflow.com/a/1116890 can be used to get the real path to the actual file

**Comment by rafaeltuelho** [comment]
adding some other issues I found running the script on mac:

* `readarray` does not exist on macosX. Maybe we need to implement the same behavior in a portable way that could work both in mac and linux.
* `xmllint` on mac seems to behave differently. Better to replace by `xmlstarlet` [1]

[1] http://xmlstar.sourceforge.net/

**Comment by hendrixback** [comment]
./runLocally.sh this work on MAC but ./runLocally.sh -i does not.
