### ISSUE TITLE
readarray: command not found

### ISSUE THREAD

**Issue by jingjielim** [kiegroup/optaweb-vehicle-routing#350]
I am running on macOS and trying to use the interactive mode.

Not sure what is wrong with the readarray command on line 275 that came with the file

Error message:
```
$ ./runLocally.sh -i
readlink: illegal option -- f
usage: readlink [-n] [file ...]

VRP dir: /Users/JingJie/.optaweb-vehicle-routing
./runLocally.sh: line 275: readarray: command not found
```

Line in question
```sh
readarray -t regions <<< "$(for r in "$osm_dir"/* "$gh_dir"/*; do basename "$r" | sed 's/.osm.pbf//'; done | sort | uniq)"
```

**Comment by yurloc** [comment]
We're aware of some issues with running the script on macOS. The problem described in #320 is different. Can you please provide the following data?
- Your macOS version.
- Your Bash version. Please run `bash --version` in a terminal and send me the output.

**Comment by jingjielim** [comment]
macOS Catalina Version 10.15.6 
```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
```

**Comment by jingjielim** [comment]
Found the issue and work around.

**Issue:**
`readarray` was introduced in bash v4 and macOS bash did not update to version 4.

**Work around:**
Install Bash 4 via Homebrew

To install Homebrew on macOS:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`

To install Bash 4:
`brew install bash`

Source: https://apple.stackexchange.com/a/193413
