### ISSUE TITLE
Region names not split correctly into arrays in runLocally.sh

### ISSUE THREAD

**Issue by jingjielim** [kiegroup/optaweb-vehicle-routing#351]
I am trying to use the interactive mode to download new OSM files. I think there is some issue in the runLocally script that is not splitting the names of the region correct. Not familiar with bash scripts so I am leaving this issue here if anyone can solve it before me.

```
  # REGION                          OSM      GRAPH    COUNTRY
==============================================================
  0 belgium-latest                  [x]        [x]         BE

Choose the next step:
d:    Download new region.
q:    Quit.
0-0: Select a region and run OptaWeb Vehicle Routing.

Your choice: d

  # REGION                               SIZE
==============================================
  0 AfricaAntarcticaAsiaAustralia and OceaniaCentral AmericaEuropeNorth AmericaSouth America    2.1 GB
Select a region (0-0) or Enter to go back: 
```

The problem probably lies with line 177 in runLocally.sh
`readarray -t region_names <<< "$(xmllint 2>>"$error_log" "$super_region_file" --html --xpath '//tr[@onmouseover]/td[1]/a/text()')"`

**Comment by dupliaka** [comment]
Thanks for that finding!
Could you please share your ` xmllint --version `

**Comment by jingjielim** [comment]
$ xmllint --version
xmllint: using libxml version 20904
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude ICU ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib

**Comment by dupliaka** [comment]
As a workaround I can suggest to update it to the 20910. With that should work fine.

**Comment by jingjielim** [comment]
Updated to 20910. Works fine now. Thank you
