### ISSUE TITLE
Non-resolvable parent POM for org.optaweb.vehiclerouting:optaweb-vehicle-routing:8.24.0-SNAPSHOT

### ISSUE THREAD

**Issue by smlcodes** [kiegroup/optaweb-vehicle-routing#718]
Getting below Error while doing mvn build, can someone pls let me know how to resolve this ?

Non-resolvable parent POM for org.optaweb.vehiclerouting:optaweb-vehicle-routing:8.24.0-SNAPSHOT: Could not transfer artifact org.optaplanner:optaplanner-build-parent:pom:8.24.0-20220616.110521-28 from/to jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/): transfer failed for https://repository.jboss.org/nexus/content/groups/public/org/optaplanner/optaplanner-build-parent/8.24.0-SNAPSHOT/optaplanner-build-parent-8.24.0-20220616.110521-28.pom, status: 503 Service Unavailable and 'parent.relativePath' points at no local POM @ line 7, column 11

**Comment by yurloc** [comment]
Unfortunately, the JBoss Nexus repository is unreliable for the past couple of weeks.

The workaround is to build the dependencies locally. In this case, please clone https://github.com/kiegroup/optaplanner and build it using `mvn clean install -nsu -Dquickly`.

For a detailed workaround procedure see https://github.com/kiegroup/optaweb-employee-rostering/issues/819#issuecomment-1147358606.

**Comment by smlcodes** [comment]
Now maven compiler it self not available .
Plugin org.apache.maven.plugins:maven-compiler-plugin:3.8.1-jboss-1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-compiler-plugin:jar:3.8.1-jboss-1: Could not transfer artifact org.apache.maven.plugins:maven-compiler-plugin:pom:3.8.1-jboss-1 from/to jboss-public-repository (https://repository.jboss.org/nexus/content/groups/public/): transfer failed for https://repository.jboss.org/nexus/content/groups/public/org/apache/maven/plugins/maven-compiler-plugin/3.8.1-jboss-1/maven-compiler-plugin-3.8.1-jboss-1.pom, status: 503 Service Unavailable

Any workaround for this ?

**Comment by smlcodes** [comment]
JBoss Nexus repository is serving from today morning. Able to build the code. Thank You @yurloc
