### ISSUE TITLE
How to send constraints to optaplanner in their unit

### ISSUE THREAD

**Issue by saif389** [kiegroup/optaweb-vehicle-routing#722]
I created a project Vehicle Routing Web Application for school buses in which I am passing three constraints : Average Speed, Allowed journey time and bus capacity to optaplanner. My issue is that how can pass my constraints like 'Average Speed in Km/h or m/s' OR 'Allowed Journey Time in minutes or seconds' to optaplanner. Please help.

**Comment by yurloc** [comment]
Closing for now. See https://www.optaplanner.org/community/getHelp.html for other ways to get help.
