### ISSUE TITLE
Remove logback.xml, use application.properties

### ISSUE THREAD

**Issue by yurloc** [kiegroup/optaweb-vehicle-routing#99]
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#boot-features-custom-log-levels

**Comment by yurloc** [comment]
OK, this is blocked by having `optaplanner-examples` as a dependency. It brings its `logback.xml` on classpath which overrides Spring Boot environment configuration described in the link above.

**Comment by Jaland** [comment]
Question is removing optaplanner-examples as a dependency something that we want to do? Look for a project and seems like that would be a way we could solve a couple of the TODOs

**Comment by yurloc** [comment]
> When possible, we recommend that you use the `-spring` variants for your logging configuration (for example, `logback-spring.xml` rather than `logback.xml`). If you use standard configuration locations, Spring cannot completely control log initialization.

https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-custom-log-configuration
